name: mala_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  archive: ^4.0.7
  dio: ^5.9.0
  get_it: ^9.2.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.2
  search_cep: ^4.0.2
  shared_preferences: ^2.5.4
  system_info2: ^4.1.0
  vit_dart_extensions: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
  test: ^1.24.0
